### ISSUE TITLE
How Plex integration work?

### ISSUE THREAD

**Issue by PaulEins** [TheWicklowWolf/ChannelTube#10]
How it work?
<img width="1466" alt="Bildschirmfoto 2024-10-04 um 16 31 01" src="https://github.com/user-attachments/assets/37bb6b80-edff-4b28-b278-13a63e6e62c1">
<img width="1467" alt="Bildschirmfoto 2024-10-04 um 16 30 52" src="https://github.com/user-attachments/assets/0b96bde6-c54f-4fa1-91ae-f41775d2d4a3">

**Comment by PaulEins** [comment]
Ok, have it anderstand? i need make new libery? so?
![Bildschirmfoto 2024-10-04 um 18 28 17](https://github.com/user-attachments/assets/d7efa623-4281-4ac7-a07b-172afd181959)
<img width="599" alt="Bildschirmfoto 2024-10-04 um 18 31 45" src="https://github.com/user-attachments/assets/7ce934d8-3b4b-480b-b51b-56c806425c6c">

**Comment by TheWicklowWolf** [comment]
Yes, you can make a library for your YouTube content. And every time new content is downloaded, a Plex library scan of that library will be initiated.
