### ISSUE TITLE
Keep Forever?

### ISSUE THREAD

**Issue by Kuroo2021** [TheWicklowWolf/ChannelTube#11]
Is there a way to set it so that the Days To Keep is the Forever Option?

![image](https://github.com/user-attachments/assets/646c7ca6-0baa-4ff4-8347-1c720621609c)

**Comment by TheWicklowWolf** [comment]
Currently, the only solution is to set "Days to Keep" to a very high value.

Note: Be aware that setting "Days to Sync" to a high value will slow down scans, as it will check for each video's presence in the folder. Once you've synced the older content, consider lowering this value to speed up future scans and focus on new videos only.
