### ISSUE TITLE
search limit and community basics

### ISSUE THREAD

**Issue by PaulEins** [TheWicklowWolf/ChannelTube#14]
Are you planning to improve this?

Because the community needs some basic functions to use it. You are a professional and very good. Many people need a little more support. And I am one of them. =)

I also have a question:
Does, “search limit” mean that you can specify how many recent videos are reviewed? I have noticed that some channels have a particularly large number of videos. If I set this value to 3 and check every hour, it is much faster.

What we would also like to see is a single manual start. Or could it even be checked via the API? So that YouTube reports to its own system and gives a notification.

If the video has just been published and ChannelTube happens to find it 1 minute later and downloads it. Then the sponsor block is not yet included. Then the video file is downloaded normally with advertising, isn't it? But if ChannelTube checks the channel again after 3 hours. Can the advertising be removed afterwards? 

If you completely delete the entry for a channel on CHannelTube, the folder with the video files will not be deleted.

Would you be happy if others fork your tool and then continue? Should they implement such small improvements? 

Your program has greatly improved my life. Now I can watch YouTube videos on my Apple TV without ads and without being influenced by the algorithm.
It was particularly difficult to avoid advertising on the Apple TV because there was hardly any interference. 

Thank you for your efforts. 
I wish you all the best.

**Comment by PaulEins** [comment]
Means this setting:
<img width="492" alt="Bildschirmfoto 2024-10-12 um 16 19 59" src="https://github.com/user-attachments/assets/816ef43b-e70b-4311-b005-689eb1a6f750">

That it looks at the last 3 entries and then only takes the last 3 days. And then keeps these 60 days and deletes them again?

I have ChannelTube check every hour. 
<img width="527" alt="Bildschirmfoto 2024-10-12 um 16 21 10" src="https://github.com/user-attachments/assets/a2b9dd79-900f-48e3-a7e4-f4d08baa134f">

**Comment by PaulEins** [comment]
If I have 120 subscriptions, I have to enter these 120 times manually. And once I have understood the settings, I have to adjust the settings manually 120 times. Unfortunately, this is very cumbersome. :-(

**Comment by PaulEins** [comment]
Can you still display the current version? And can ChannelTub itself indicate whether there is a newer version?
Paperless does this very well. It's at the bottom left. Current version and a note whether there is a newer version. Because then you can go directly to Portianer and update.

**Comment by PaulEins** [comment]
Could it be that the item counts incorrectly at the beginning?

When you create the channel, it says 0. If you then run it manually and it recognizes a new video, it still says 0, but it downloads the video. After that it has found 1 video but it still says 0. 
It's not so important now, but when I have created all this, it says 0, 0, 0 everywhere, but there are already videos in Plex. =)

**Comment by PaulEins** [comment]
And I've noticed that if I activate it manually just before the schedule, it does the whole thing twice. Then it also downloads the videos twice. 
<img width="929" alt="Bildschirmfoto 2024-10-12 um 17 00 20" src="https://github.com/user-attachments/assets/dc8e0f6d-82aa-4eb2-b0c6-373c868b8530">
<img width="971" alt="Bildschirmfoto 2024-10-12 um 17 01 09" src="https://github.com/user-attachments/assets/9a0d6496-d344-45df-8ca2-656a17c4c066">

Or is it possible that it still creates the folder, but not the way you entered it? If you change the name, does it make an additional standard entry? I've often had it create two channels. One original, and one with its own assigned name. 

<img width="1096" alt="Bildschirmfoto 2024-10-12 um 17 04 32" src="https://github.com/user-attachments/assets/06ac403e-d6bf-488d-8188-8125c10a2d5d">

**Comment by TheWicklowWolf** [comment]
**A few notes:**
- This project is designed to be as simple as possible, with minimal features, following a "set it and forget it" philosophy.
- You can defer downloads by setting an environmental variable.
- The current version is logged  in the container logs and can be viewed with something like dozzle
- I'd suggest Watchtower to keep it automatically updated.
- The search limit controls how many videos are checked.
- Settings are saved in a text file, allowing you to adjust everything at once. (A container restart is required for changes to take effect.)
- The item count simply indicates the number of items at the end of each scan.
- Changing the folder name (in the UI or filesystem) will result in duplicates.
- Feel free to fork the project to customize it to your needs. I'm also open to pull requests.
---

For more feature-rich alternatives that might better suit your needs, consider these options:

- [TubeArchivist](https://github.com/tubearchivist/tubearchivist)
- [TubeSync](https://github.com/meeb/tubesync)
- [YouTubeDL-Material](https://github.com/Tzahi12345/YoutubeDL-Material)
- [Pinchflat](https://github.com/kieraneglin/pinchflat)
- [ytdlp-material](https://github.com/jmbannon/ytdl-sub)

Best of luck!
