### ISSUE TITLE
Exclude 4K (VP9) because it doesn't work with Plex and the Apple TV

### ISSUE THREAD

**Issue by PaulEins** [TheWicklowWolf/ChannelTube#15]
The highest possible quality is automatically loaded for a channel. For the [Chibo](https://www.youtube.com/@ChiboOfficial) channel, it is 4k with 50 frames per second and everything in **VP9**. But unfortunately it is jerky on the Apple TV 4k in the Plex app.

**Where exactly do I have to change this?**
Can I set globally what resolution I want? For all? Or can I specify the format for each subscription?

Here? 
<img width="513" alt="Bildschirmfoto 2024-10-21 um 04 13 23" src="https://github.com/user-attachments/assets/06b9907f-8995-4ed1-9bd8-924c33e49f59">

That would be something that could be implemented. Perhaps make the form window for each channel a little wider and larger. That would help me.

**Comment by TheWicklowWolf** [comment]
Sounds like a hardware issue, as your server cannot transcode the files in realtime.

---
## **From the readme**...
>
> Certain values can be set via environment variables:
>
> * __video_format_id__: Specifies the ID for the video format. The default value is `137`.
> * __audio_format_id__: Specifies the ID for the audio format. The default value is `140`.
> * __defer_hours__: Defines the time to defer in hours. The default value is `0`.
> * __thread_limit__: Sets the maximum number of threads to use. The default value is `1`.
>
> For information on format IDs, refer to [https://github.com/yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp)

**Comment by PaulEins** [comment]
I have inserted this, but it does not work. The files are the same. Is this the right way to do it?
<img width="806" alt="Bildschirmfoto 2024-10-23 um 16 07 06" src="https://github.com/user-attachments/assets/645b5e0e-837e-4efb-bd5b-667749d4a601">
