### ISSUE TITLE
Requested format is not available

### ISSUE THREAD

**Issue by kel-mo** [TheWicklowWolf/ChannelTube#3]
Hi TheWickloWolf,

I'm getting a fair few of these errors:

> channeltube  | Starting Downloading List: mostlychris
> channeltube  | Starting Download: AMAZING new UI with timeline scrubbing, real time motion tuning, and authentication.
> channeltube  | yt_dl Start: https://www.youtube.com/watch?v=NMzKsBFN-6k
> channeltube  | ERROR: [youtube] NMzKsBFN-6k: Requested format is not available. Use --list-formats for a list of available formats
> channeltube  | Error downloading video: https://www.youtube.com/watch?v=NMzKsBFN-6k. Error message: ERROR: [youtube] NMzKsBFN-6k: Requested format is not available. Use --list-formats for a list of available formats

Same error for this vid and a few others I subscribe to: https://www.youtube.com/watch?v=gvq5wirhaUk

1080p60 appears to be the the common denominator for those that fail.

**Comment by TheWicklowWolf** [comment]
I forgot to add a fallback option... 

Updated now, so if the selected format is not available it picks the best video and audio format.

You can update using `docker compose pull && docker compose up -d`
